export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN";
export const LOGIN_CUSTOM_RESPONSE = "LOGIN_CUSTOM_RESPONSE";
export const LOGIN_HTTP_RESPONSE = "LOGIN_HTTP_RESPONSE";
export const ROLE_LIST_RESPONSE = 'ROLE_LIST_RESPONSE';
export const USER_LIST_RESPONSE = 'USER_LIST_RESPONSE ';
export const USER_LIST = 'USER_LIST ';
export const ROLE_LIST = 'ROLE_LIST ';


export const WALLET_LIST = 'WALLET_LIST '
export const WALLET_LIST_RESPONSE = 'WALLET_LIST_RESPONSE '
export const MINT_GAS = 'MINT_GAS '
export const MINT_GAS_RESPONSE = 'MINT_GAS_RESPONSE';
export const MINT_REQUEST = 'MINT_REQUEST';
export const UPDATE_NFT_REQUEST = 'UPDATE_NFT_REQUEST';
export const NFT_SINGLE_LIST_RESPONSE = 'NFT_SINGLE_LIST_RESPONSE';
export const NFT_SINGLE_LIST = 'NFT_SINGLE_LIST';



